# Generated by Django 5.0.6 on 2024-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='shift_type',
            field=models.CharField(choices=[('cart', 'Cart'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(),
        ),
    ]
