# Generated by Django 5.0.6 on 2024-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_shift_type_alter_tip_amount_alter_tip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
            preserve_default=False,
        ),
    ]
